### ISSUE TITLE
iCE40?  Parallel memory?

### ISSUE THREAD

**Issue by GravisZro** [dshadoff/PCE_Save128#1]
Just curious if you might be interested in perhaps modifying the project to use a Lattice iCE40 chip (e.g. [ICE40HX1K-VQ100](https://www.digikey.com/en/products/detail/lattice-semiconductor-corporation/ICE40HX1K-VQ100/3083577)) since there is [an open source toolchain](http://www.clifford.at/icestorm/) and perhaps avoid SPI altogether by using a memory chip with a parallel interface (e.g. [MR0A08BYS35](https://www.digikey.com/en/products/detail/everspin-technologies-inc/MR0A08BYS35/1930954)).  Yes, the iCE40 will need another power regulator but it's not too complex.  There is [a cheap iCE40 dev board](http://www.latticesemi.com/icestick) you can get if that is a concern.

Just some ideas to consider but if you're not interested in making changes, that's OK too.

**Comment by dshadoff** [comment]
I had considered iCE40 originally because it's so accessible to hobbyists.
However, it requires external flash for configuration memory, as well as multiple supplies and a specific power-up sequence.
And the miserable QFN-32 package gets replaced by an even more miserable QFN-48 package.

So, ease of programming is counteracted by difficulty in design/assembly.

Don't worry, I have another solution coming soon which simplifies a bit.

**Comment by GravisZro** [comment]
Ugh... QFN is the worst.  Looking forward to the new solution.
